### PR TITLE
Indexers: Add HDBits

### PR DESCRIPTION
**Pull request by AlexKvM**
Tested it briefly and it should work now:

```
2022-01-23T04:47:56+07:00 DBG irc.p2p-network.net: #hdbits.announce midgards: New Torrent: Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly - Type: TV (HEVC, WEB-DL) - Uploaded by: Anonymous - Size: 52.83 GiB - https://hdbits.org/details.php?id=600030&hit=1
2022-01-23T04:47:56+07:00 TRC announce: queued line: New Torrent: Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly - Type: TV (HEVC, WEB-DL) - Uploaded by: Anonymous - Size: 52.83 GiB - https://hdbits.org/details.php?id=600030&hit=1
2022-01-23T04:47:56+07:00 TRC announce: process line: New Torrent: Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly - Type: TV (HEVC, WEB-DL) - Uploaded by: Anonymous - Size: 52.83 GiB - https://hdbits.org/details.php?id=600030&hit=1
2022-01-23T04:47:56+07:00 TRC filter-service.find_and_check_filters: found (1) active filters to check for indexer 'hdb'
2022-01-23T04:47:56+07:00 TRC filter-service.find_and_check_filters: checking filter: test hdb
2022-01-23T04:47:56+07:00 DBG filter-service.find_and_check_filters: found and matched filter: test hdb
2022-01-23T04:47:56+07:00 DBG filter-service.find_and_check_filters: (test hdb) additional size check required
2022-01-23T04:47:56+07:00 TRC filter-service.find_and_check_filters: (test hdb) additional size check required: preparing to download metafile
2022-01-23T04:47:57+07:00 DBG successfully downloaded file: /var/folders/k5/lt15z_x127b8y36prz5rrjd00000gn/T/autobrr-1935447707
2022-01-23T04:47:57+07:00 TRC release.store: &{ID:5 FilterStatus:FILTER_APPROVED Rejections:[] Indexer:hdb FilterName:test hdb Protocol:torrent Implementation:IRC Timestamp:2022-01-23 04:47:56.982097 +0700 +07 m=+1513.522181126 GroupID: TorrentID:600030 TorrentURL:https://hdbits.org/download.php?id=600030&passkey=12345 TorrentTmpFile:/var/folders/k5/lt15z_x127b8y36prz5rrjd00000gn/T/autobrr-1935447707 TorrentName:Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly Size:56725162316 Raw: Clean:Squid Game S01 2160p WEB DL DD+5 1 HDR HEVC Telly Title: Category:TV Season:1 Episode:0 Year:0 Resolution:2160p Source:WEB-DL Codec:HEVC Container: HDR:HDR Audio:DD Group:Telly Region: Language: Edition: Unrated:false Hybrid:false Proper:false Repack:false Website: ThreeD:false Artists:[] Type: Format: Quality: LogScore:0 HasLog:false HasCue:false IsScene:false Origin: Tags:[] ReleaseTags:HEVC, WEB-DL Freeleech:false FreeleechPercent:0 Uploader:Anonymous PreTime: AdditionalSizeCheckRequired:true FilterID:1 Filter:0x140000f0900 ActionStatus:[]}
2022-01-23T04:47:57+07:00 INF Matched 'Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly' (test hdb) for hdb
2022-01-23T04:47:57+07:00 TRC start to process release: {ID:5 FilterStatus:FILTER_APPROVED Rejections:[] Indexer:hdb FilterName:test hdb Protocol:torrent Implementation:IRC Timestamp:2022-01-23 04:47:56.982097 +0700 +07 m=+1513.522181126 GroupID: TorrentID:600030 TorrentURL:https://hdbits.org/download.php?id=600030&passkey=12345 TorrentTmpFile:/var/folders/k5/lt15z_x127b8y36prz5rrjd00000gn/T/autobrr-1935447707 TorrentName:Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly Size:56725162316 Raw: Clean:Squid Game S01 2160p WEB DL DD+5 1 HDR HEVC Telly Title: Category:TV Season:1 Episode:0 Year:0 Resolution:2160p Source:WEB-DL Codec:HEVC Container: HDR:HDR Audio:DD Group:Telly Region: Language: Edition: Unrated:false Hybrid:false Proper:false Repack:false Website: ThreeD:false Artists:[] Type: Format: Quality: LogScore:0 HasLog:false HasCue:false IsScene:false Origin: Tags:[] ReleaseTags:HEVC, WEB-DL Freeleech:false FreeleechPercent:0 Uploader:Anonymous PreTime: AdditionalSizeCheckRequired:true FilterID:1 Filter:0x140000f0900 ActionStatus:[]}
2022-01-23T04:47:57+07:00 DBG process action: new action for 'Squid Game S01 2160p WEB-DL DD+5.1 HDR HEVC-Telly'
2022-01-23T04:47:57+07:00 TRC events: 'release:store-action-status' '&{ID:0 Status:PENDING Action:new action Type:TEST Rejections:[] Timestamp:2022-01-23 04:47:57.625292 +0700 +07 m=+1514.165372042 ReleaseID:5}'
2022-01-23T04:47:57+07:00 TRC release.store_release_action_status: &{ID:5 Status:PENDING Action:new action Type:TEST Rejections:[] Timestamp:2022-01-23 04:47:57.625292 +0700 +07 m=+1514.165372042 ReleaseID:5}
2022-01-23T04:47:57+07:00 INF action TEST: new action
2022-01-23T04:47:57+07:00 TRC events: 'release:store-action-status' '&{ID:5 Status:PUSH_APPROVED Action:new action Type:TEST Rejections:[] Timestamp:0001-01-01 00:00:00 +0000 UTC ReleaseID:5}'
2022-01-23T04:47:57+07:00 TRC release.store_release_action_status: &{ID:5 Status:PUSH_APPROVED Action:new action Type:TEST Rejections:[] Timestamp:0001-01-01 00:00:00 +0000 UTC ReleaseID:5}
```

But it looks like autobrr still downloads the torrent even if the size is parsed correctly.
Also it might be a good idea to add a flag for internal releases just like the freeleech flag.

### CODE REVIEW

**Comment by ludviglundgren** [comment]
Thanks Alex! It's indeed weird that it's triggering a download file even tho it's there in the announce. I'll do some local testing and see if there's potentially other bugs from the last days.

**Comment by brettpetch** [comment]
For the record, HDB does have an API endpoint that could be utilized for sizecheck

/b

**Review by ludviglundgren — APPROVED** [review]
A couple minor changes, and a big one. To parse size correctly the variable needs to be `torrentSize`. Could you try it out again and see if it works as intended now without it downloading the file to parse size? @AlexKvM :slightly_smiling_face:

**Comment by AlexKvM** [comment]
Yes, it doesn't download a torrent now, also fixed the variable name and updated regex to expect non-empty strings in category, etc.

**Comment by ludviglundgren** [comment]
Great!! Then I'll merge this 🙂👍

**Pull request merged**
