### PR TITLE
feat(filters): regex validation for supported fields

### PR DESCRIPTION
**Pull request by s0up4200**
## Regex validation for regex supported fields

This PR adds regex validation to `Match releases`, `Except releases`, `Match release tags` and `Except release tags`.
Green and red checkmarks will display whenever the `Use regex`switches are toggled.

Added Formik Validation. You can no longer save when regex is invalid (if the regex switch is enabled)

Demonstration: https://cln.sh/QyLlr082

It _should_ check for Golang flavor, but would like someone to look that over.

### CODE REVIEW

**Review by zze0s — COMMENTED** [review]
I think it makes more sense to create a new field like `RegexField` or similar that has the regex things in it, rather than adding very specific functionality to a common field.

**Comment by s0up4200** [comment]
> I think it makes more sense to create a new field like `RegexField` or similar that has the regex things in it, rather than adding very specific functionality to a common field.

Done!

**Comment by zze0s** [comment]
> > I think it makes more sense to create a new field like `RegexField` or similar that has the regex things in it, rather than adding very specific functionality to a common field.
> 
> Done!

Great! Further improvements could be to use the built in functionality in Formik Fields for validation. 

- https://formik.org/docs/guides/validation#field-level-validation
- https://www.digitalocean.com/community/tutorials/how-to-validate-a-login-form-with-react-and-formik

**Comment by s0up4200** [comment]
> > > I think it makes more sense to create a new field like `RegexField` or similar that has the regex things in it, rather than adding very specific functionality to a common field.
> > 
> > 
> > Done!
> 
> Great! Further improvements could be to use the built in functionality in Formik Fields for validation.
> 
>     * https://formik.org/docs/guides/validation#field-level-validation
> 
>     * https://www.digitalocean.com/community/tutorials/how-to-validate-a-login-form-with-react-and-formik

Should be good now 👍

**Review by zze0s — APPROVED** [review]
Made some improvements like discussed!

**Pull request merged**
