### PR TITLE
feat(indexers): add Aither

### PR DESCRIPTION
**Pull request by s0up4200**
Add Aither

ref https://github.com/autobrr/autobrr/issues/1

Thank you @nuxencs for assisting with the regex pattern 😃

### CODE REVIEW

**Comment by quorn23** [comment]
`Url \[(https?\:\/\/.+\/).+/(\d+)\]` is unescaped, needs to be 

`Url \[(https?\:\/\/.+\/).+\/(\d+)\]`

Ref: [https://regex101.com/r/M1VF5s/1](https://regex101.com/r/M1VF5s/1)

**Comment by p8757181** [comment]
The regex will need a further change to make the resolution tag optional for non-TV/Film content.

Example from the feed:

```
Category [Music] Type [Music - General] Name [Kanye West - Yeezus 2013 WEB FLAC 16-bits 44.1 kHz] Resolution [] Freeleech [0%] Internal [No] Double Upload [No] Size [258.07 MB] Uploader [Pure] Url [https://aither.cc/torrents/download/63728]
```

**Comment by s0up4200** [comment]
@p8757181 

You can use this for now:

```
  parse:
    type: single
    lines:
      - test:
          - "Category [Movie] Type [WEB-DL] Name [A Guide to Dating at the End of the World 2022 1080p AMZN WEB-DL DD+ 5.1 H.264-THR] Resolution [1080p] Freeleech [0%] Internal [No] Double Upload [No] Size [5.13 GB] Uploader [Anonymous] Url [https://aither.cc/torrents/download/63267]"
        pattern: 'Category \[(.+)\] Type \[(.+)\] Name \[(.+)\] Resolution \[(.+)\] Freeleech \[(.+)\] Internal \[(.+)\] Double Upload \[(.+)\] Size \[(.+)\] Uploader \[(.+)\] Url \[(https?\:\/\/.+\/).+/(\d+)\]'
        vars:
          - category
          - releaseTags
          - torrentName
          - resolution
          - freeleechPercent
          - internal
          - tags
          - torrentSize
          - uploader
          - baseUrl
          - torrentId
```

**Comment by s0up4200** [comment]
@p8757181 We heard there might be more changes coming to the announces so we're holding off a bit.

You can use this one as a custom definition until the devs have decided no more changes are happening: https://bin.r4tio.dev/otomogutak.yaml

How to use custom indexer definitions: https://autobrr.com/configuration/indexers#custom-indexer-definitions

**Comment by martylukyy** [comment]
🚀

**Review by martylukyy — APPROVED** [review]
The whitespace after the name capture group is now optional since there is the possibility that the resolution part of the announce is missing in case there can be no resolution given for a release. (see the optional non-capturing group)
This however resulted in name capture group capturing way too much up until the closing square bracket after the resolution. 
To fix this the quantifier for the name capture group is now lazy/ungreedy `(.+?)` so that regex will not capture everything up until the square bracket for the resolution.
For more than one whitespace after the name capture group (in case the resolution part is missing) has been accounted for.
An empty bracket for the resolution part has also been accounted for.

**Review by zze0s — APPROVED** [review]

**Pull request merged**
