### PR TITLE
feat(filter): implement unique downloads

### PR DESCRIPTION
**Pull request by KyleSanderson**
first time using goland, there's a bunch of whitespace that it seems to add in the IDE... not sure if it's actually written to the file.

### CODE REVIEW

**Comment by zze0s** [comment]
It's a good start but I converted it into a draft again since this needs more work done.

- Implemented in the filter logic
- Tests

**Comment by luckylittle** [comment]
Can we get this merged @zze0s ?

**Comment by zze0s** [comment]
It still needs more work.

**Comment by zze0s** [comment]
Superseded by https://github.com/autobrr/autobrr/pull/1539

**Pull request closed without merging**
