### PR TITLE
feat(auth): change password and username

### LINKED ISSUE #1292: [FEATURE REQ] Unable to change password when using env vars and no config file
**Version**

v1.34.0

**Describe the bug**

Maybe more a feature request than a bug, feel free to update the label if needed.

I have all my config defined via env vars and I am unable to change the password for my user

```
kubectl exec -it autobrr-69d55f876d-cfh94 -- sh
/app $ autobrrctl change-password user
2023/12/01 19:19:41 --config required
```

**To Reproduce**

Deploy autobrr via env vars without a config file

**Expected behavior**

I am able to change my password via `autobrrctl change-password` by the command reading from env

**Additional context**

It would be great if you could change the password via the UI instead.

### PR DESCRIPTION
**Pull request by KaiserBh**
closes #1292 

Added setting option that goes to profile where they can change their password and potentially username, feel free to change the the layout or modify the design. 

Also for now I disabled the username field but we can update them as well if we want, just need to add a hidden field that send the current username and new username to the backend.

change-password

### CODE REVIEW

**Review by KyleSanderson — COMMENTED** [review]
So close - nice one man.

There was another request to change usernames, both are fairly rare but maybe something to consider if you feel like it.

**Review by KyleSanderson — DISMISSED** [review]

**Comment by s0up4200** [comment]
CleanShot 2023-12-18 at 11 18 42@2x
CleanShot 2023-12-18 at 11 19 01@2x

**Comment by KaiserBh** [comment]
I was thinking more that we should use one endpoint for updating user, usually something like this;
If the user provide the new username then it's safe to assume they want to update their username, and they have to provide their current password to update them regardless. 

It will be cleaner and everything in one place;
- current username field (disabled which will be sent to back end as well)
- new username (optional field)
- current password (required for any changes that's being made.)
- new password (optional)
- confirm password (optional)
- Button which can be called "UPDATE USER" or something meaningful.

**Comment by s0up4200** [comment]
> I was thinking more that we should use one endpoint for updating user, usually something like this; If the user provide the new username then it's safe to assume they want to update their username, and they have to provide their current password to update them regardless.
> 
> It will be cleaner and everything in one place;
> 
>     * current username field (disabled which will be sent to back end as well)
> 
>     * new username (optional field)
> 
>     * current password (required for any changes that's being made.)
> 
>     * new password (optional)
> 
>     * confirm password (optional)
> 
>     * Button which can be called "UPDATE USER" or something meaningful.

Agreed! I'll try, unless you want to yourself?

**Comment by s0up4200** [comment]
UI can definitely be improved, but made a single endpoint that handles both now.
newUsername and newPassword are now optional, the user can change either or both this way.

CleanShot 2023-12-18 at 14 01 17@2x
CleanShot 2023-12-18 at 14 01 40@2x

**Comment by KaiserBh** [comment]
:ono: Sorry my internet sucks and didn't realise my reply didn't go through @s0up4200, moved house recently so still waiting for wifi, and using my mobile data currently. New house have really bad reception :( 1mbps gang.

**Comment by KaiserBh** [comment]
newuser

**Comment by s0up4200** [comment]
CleanShot 2023-12-18 at 20 51 03
CleanShot 2023-12-18 at 20 40 58@2x
CleanShot 2023-12-18 at 20 41 57@2x

**Review by s0up4200 — DISMISSED** [review]

**Comment by s0up4200** [comment]
CleanShot 2023-12-18 at 22 11 50@2x
CleanShot 2023-12-18 at 22 11 23@2x

**Review by zze0s — APPROVED** [review]
Great addition! 

I refactored a few things on the backend :smile: 

* It now has more generic UpdateUser methods instead of being specific like UpdateUserCredentials
* autobrrctl minor refactor
* Changed the endpoint to update user to `PATCH /auth/user/{username}`. No need at this point for a separate userHandler

**Pull request merged**
