### PR TITLE
feat(indexers): add AnimeWorld

### PR DESCRIPTION
**Pull request by Pheromir**
# Indexer request

-  Do they have irc announce? Yes
- Indexer name: AnimeWorld
- Short name: AW
- URL: https://animeworld.cx
- Download link example: https://animeworld.cx/torrent/download/00000.{rss_key}

## Announce examples

(Release names slightly modified to not use any real but very similar releasenames)

- `Neuer Upload: Magic.S02E10.Ger.Eng.Sub.AAC.1080p.WEB.h264-ABC [Kategorie: Anime Serien][Typ: WebDL][Auflösung: 1080p][Größe: 1.35 GB][FL: 100%] | https://animeworld.cx/torrents/00000 | Uploader: NotAnonymous`
- `Neuer Upload: The.Zero.S04.German.DL.DTS.1080p.BluRay.10bit.x265.Repack-ABC [Kategorie: Anime Serien][Typ: Encode][Auflösung: 1080p][Größe: 17.28 GiB][FL: 100%][Vorgestellt] | https://animeworld.cx/torrents/00000 | Uploader: Anonym`
- `Neuer Upload: How.to.Train.2010.German.DL.AC3.1080p.BluRay.x264-ABC [Kategorie: Cartoon Filme][Typ: Encode][Auflösung: 1080p][Größe: 3.45 GiB][FL: 0%] | https://animeworld.cx/torrents/00000 | Uploader: Anonym`
- `Neuer Upload: Irgendein Testrelease ohne Schema [Kategorie: H-Manga / Doujinshi][Typ: Digital][Auflösung: No Res][Größe: 673.21 MiB][FL: 0%] | https://animeworld.cx/torrents/00000 | Uploader: Anonym`

## IRC Network

- Network name: Rizon
- Network address: irc.rizon.net
- Port: 6697
- SSL/TLS: Yes
- NickServ registration required? Yes
- Is there a required format for the nick? Username|Bot or Username_Bot
- Invite command: None, currently only with a global channel password
(Its possible to add a required password in the settings of the irc network - should that be used or `/join #animeworld password` as an "invite" command instead?)

### Categories:
- Anime Filme
- Anime Serien
- Anime Musik / OSTs
- Anime Spiele
- Anime Hentai
- Software
- Sonstiges
- Filme
- Serien
- Spiele
- Musik
- Manga
- Cartoon Filme
- Cartoon Serie
- H-Manga / Doujinshi

### Types:
- Untouched
- Remux
- Encode
- WebDL
- WebRip
- HDTV
- TVRip
- Lossless Audio
- Lossy Audio
- Scans
- Digital
- Windows
- Mac
- Linux
- Konsole

### CODE REVIEW

**Review by martylukyy — APPROVED** [review]
Good to merge.

Note:
As a general improvement it would be good to add a channel password setting for the indexer definitions since we have at least 2 indexers with channel passwords now.

**Review by martylukyy — DISMISSED** [review]
Good to merge.
Did some further improvements.

Note:
As a general improvement it would be good to add a channel password setting for the indexer definitions since we have at least 2 indexers with channel passwords now.

**Comment by zze0s** [comment]
Rel https://github.com/autobrr/autobrr/pull/1473

**Review by martylukyy — APPROVED** [review]
Now it's perfect!
Thanks!

**Review by zze0s — APPROVED** [review]

**Pull request merged**
