### PR TITLE
feat(notifications): add Pushover

### PR DESCRIPTION
**Pull request by nelsonpecora**
This PR adds Pushover notifications support to Autobrr. Users can set their desired `api_key`, `user_key`, and `priority` in the settings.

### CODE REVIEW

**Review by s0up4200 — CHANGES_REQUESTED** [review]
Needs changes to postgres_migrate.go

**Review by s0up4200 — APPROVED** [review]

**Comment by buroa** [comment]
Can we get this merged? Looks like the build failed because of a 403.

```
ERROR: failed to solve: failed to push ghcr.io/autobrr/autobrr:pr-598: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/autobrr/autobrr:pr-598: unexpected status: 403 Forbidden
```

**Comment by s0up4200** [comment]
This hasn't been fully tested yet. The test function works and sends those notifications, but it should probably be tested with "real data" before a merge.

**Review by zze0s — APPROVED** [review]
Thanks for the PR and sorry about the 5 month wait :sweat_smile: 

I made some changes, primarily priority from a string to integer, so you'll have to update your instance @nelsonpecora

Also some other minor changes:
- only test enabled events
- initial schema migrations

Tested it myself and it works as intended!

**Comment by buroa** [comment]
Thanks for this update!! 🥇

**Pull request merged**
