### PR TITLE
feat(web): make PWA compatible with Vite

### PR DESCRIPTION
**Pull request by KaiserBh**
Added PWA (Progressive Web App) support, works fine on my end do test it tho, Also made it autoInject and autoUpdate that way it just automatically "updates" instead of prompting user (otherwise we need to register it manually and make the prompt etch which isn't hard but for the type of app we have here it's not needed.)

Requires https://github.com/autobrr/autobrr/pull/787 to be merged first.

### CODE REVIEW

**Comment by KaiserBh** [comment]
> Could you rebase your feature branch onto an updated develop in your fork, or close this and open a new PR? @KaiserBh 

Yea, for sure. I will probably open a new PR, hopefully tomorrow until then, I will just leave this open for now.

**Review by zze0s — COMMENTED** [review]
Are all those 40 apple-only logos _actually_ needed?

**Comment by KaiserBh** [comment]
> Are all those 40 apple-only logos _actually_ needed?

not sure honestly I just added what @s0up4200 had. @s0up4200 do we need those 40 apple-only logos?

**Comment by s0up4200** [comment]
> > Are all those 40 apple-only logos _actually_ needed?
> 
> not sure honestly I just added what @s0up4200 had. @s0up4200 do we need those 40 apple-only logos?

Probably not. The generator I used made them all. Just delete those from older models I guess?

**Review by zze0s — APPROVED** [review]

**Pull request merged**
