### PR TITLE
enhancement(web): specify error message when not choosing a client

### PR DESCRIPTION
**Pull request by martylukyy**
Every now an then we get questions about following error message:
`{"message":"json: cannot unmarshal string into Go struct field Action.actions.client_id of type int32"}`
So i went ahead and caught the error to replace it with a understandable one:

image

### CODE REVIEW

**Review by s0up4200 — APPROVED** [review]
Good change 👍

**Comment by stacksmash76** [comment]
Nope from me. Backend boys need to fix their shit and provide an interface to standardized error messages.

**Comment by KaiserBh** [comment]
> Nope from me. Backend boys need to fix their shit and provide an interface to standardized error messages.

yea agreed, the client/frontend don't need to know what error exactly happened, because that's what logs are for, so we need to send proper error messages to the clients etc, that way the frontend don't need to do so much hacky stuff everything will be streamlined that way.

**Comment by zze0s** [comment]
More proper fix with frontend validation using Zod. https://github.com/autobrr/autobrr/pull/888

**Pull request closed without merging**
